#ifdef NS3_MODULE_COMPILATION 
    error "Do not include ns3 module aggregator headers from other modules these are meant only for end user scripts." 
#endif 
#ifndef NS3_MODULE_NR
    // Module headers: 
    #include <ns3/beamforming-helper-base.h>
    #include <ns3/cc-bwp-helper.h>
    #include <ns3/file-scenario-helper.h>
    #include <ns3/grid-scenario-helper.h>
    #include <ns3/hexagonal-grid-scenario-helper.h>
    #include <ns3/ideal-beamforming-helper.h>
    #include <ns3/node-distribution-scenario-interface.h>
    #include <ns3/nr-bearer-stats-calculator.h>
    #include <ns3/nr-bearer-stats-connector.h>
    #include <ns3/nr-bearer-stats-simple.h>
    #include <ns3/nr-epc-helper.h>
    #include <ns3/nr-helper.h>
    #include <ns3/nr-mac-rx-trace.h>
    #include <ns3/nr-mac-scheduling-stats.h>
    #include <ns3/nr-no-backhaul-epc-helper.h>
    #include <ns3/nr-phy-rx-trace.h>
    #include <ns3/nr-point-to-point-epc-helper-base.h>
    #include <ns3/nr-point-to-point-epc-helper.h>
    #include <ns3/nr-radio-environment-map-helper.h>
    #include <ns3/nr-spectrum-value-helper.h>
    #include <ns3/nr-stats-calculator.h>
    #include <ns3/realistic-beamforming-helper.h>
    #include <ns3/scenario-parameters.h>
    #include <ns3/three-gpp-ftp-m1-helper.h>
    #include <ns3/bandwidth-part-gnb.h>
    #include <ns3/bandwidth-part-ue.h>
    #include <ns3/beam-id.h>
    #include <ns3/beam-manager.h>
    #include <ns3/beamforming-vector.h>
    #include <ns3/bwp-manager-algorithm.h>
    #include <ns3/bwp-manager-gnb.h>
    #include <ns3/bwp-manager-ue.h>
    #include <ns3/ideal-beamforming-algorithm.h>
    #include <ns3/lena-error-model.h>
    #include <ns3/nr-a2-a4-rsrq-handover-algorithm.h>
    #include <ns3/nr-a3-rsrp-handover-algorithm.h>
    #include <ns3/nr-tn-ntn-handover-algorithm.h>
    #include <ns3/nr-amc.h>
    #include <ns3/nr-anr.h>
    #include <ns3/nr-anr-sap.h>
    #include <ns3/nr-as-sap.h>
    #include <ns3/nr-asn1-header.h>
    #include <ns3/nr-cb-two-port.h>
    #include <ns3/nr-cb-type-one-sp.h>
    #include <ns3/nr-cb-type-one.h>
    #include <ns3/nr-ccm-mac-sap.h>
    #include <ns3/nr-ccm-rrc-sap.h>
    #include <ns3/nr-ch-access-manager.h>
    #include <ns3/nr-chunk-processor.h>
    #include <ns3/nr-common.h>
    #include <ns3/nr-component-carrier.h>
    #include <ns3/nr-control-messages.h>
    #include <ns3/nr-eesm-cc-t1.h>
    #include <ns3/nr-eesm-cc-t2.h>
    #include <ns3/nr-eesm-cc.h>
    #include <ns3/nr-eesm-error-model.h>
    #include <ns3/nr-eesm-ir-t1.h>
    #include <ns3/nr-eesm-ir-t2.h>
    #include <ns3/nr-eesm-ir.h>
    #include <ns3/nr-eesm-t1.h>
    #include <ns3/nr-eesm-t2.h>
    #include <ns3/nr-epc-gnb-application.h>
    #include <ns3/nr-epc-gnb-s1-sap.h>
    #include <ns3/nr-epc-gtpc-header.h>
    #include <ns3/nr-epc-gtpu-header.h>
    #include <ns3/nr-epc-mme-application.h>
    #include <ns3/nr-epc-pgw-application.h>
    #include <ns3/nr-epc-s11-sap.h>
    #include <ns3/nr-epc-s1ap-sap.h>
    #include <ns3/nr-epc-sgw-application.h>
    #include <ns3/nr-epc-tft-classifier.h>
    #include <ns3/nr-epc-tft.h>
    #include <ns3/nr-epc-ue-nas.h>
    #include <ns3/nr-epc-x2-header.h>
    #include <ns3/nr-epc-x2-sap.h>
    #include <ns3/nr-epc-x2.h>
    #include <ns3/nr-eps-bearer-tag.h>
    #include <ns3/nr-eps-bearer.h>
    #include <ns3/nr-error-model.h>
    #include <ns3/nr-fh-control.h>
    #include <ns3/nr-fh-sched-sap.h>
    #include <ns3/nr-fh-phy-sap.h>
    #include <ns3/nr-gnb-cmac-sap.h>
    #include <ns3/nr-gnb-component-carrier-manager.h>
    #include <ns3/nr-gnb-cphy-sap.h>
    #include <ns3/nr-gnb-mac.h>
    #include <ns3/nr-gnb-net-device.h>
    #include <ns3/nr-gnb-phy.h>
    #include <ns3/nr-gnb-rrc.h>
    #include <ns3/nr-handover-algorithm.h>
    #include <ns3/nr-handover-management-sap.h>
    #include <ns3/nr-harq-phy.h>
    #include <ns3/nr-interference-base.h>
    #include <ns3/nr-interference.h>
    #include <ns3/nr-lte-amc.h>
    #include <ns3/nr-lte-mi-error-model.h>
    #include <ns3/nr-mac-csched-sap.h>
    #include <ns3/nr-mac-harq-process.h>
    #include <ns3/nr-mac-harq-vector.h>
    #include <ns3/nr-mac-header-fs-dl.h>
    #include <ns3/nr-mac-header-fs-ul.h>
    #include <ns3/nr-mac-header-fs.h>
    #include <ns3/nr-mac-header-vs-dl.h>
    #include <ns3/nr-mac-header-vs-ul.h>
    #include <ns3/nr-mac-header-vs.h>
    #include <ns3/nr-mac-pdu-info.h>
    #include <ns3/nr-mac-sap.h>
    #include <ns3/nr-mac-sched-sap.h>
    #include <ns3/nr-mac-scheduler-cqi-management.h>
    #include <ns3/nr-mac-scheduler-harq-rr.h>
    #include <ns3/nr-mac-scheduler-lc-alg.h>
    #include <ns3/nr-mac-scheduler-lc-qos.h>
    #include <ns3/nr-mac-scheduler-lc-rr.h>
    #include <ns3/nr-mac-scheduler-lcg.h>
    #include <ns3/nr-mac-scheduler-ns3.h>
    #include <ns3/nr-mac-scheduler-ofdma-mr.h>
    #include <ns3/nr-mac-scheduler-ofdma-pf.h>
    #include <ns3/nr-mac-scheduler-ofdma-qos.h>
    #include <ns3/nr-mac-scheduler-ofdma-rr.h>
    #include <ns3/nr-mac-scheduler-ofdma.h>
    #include <ns3/nr-mac-scheduler-srs-default.h>
    #include <ns3/nr-mac-scheduler-srs.h>
    #include <ns3/nr-mac-scheduler-tdma-mr.h>
    #include <ns3/nr-mac-scheduler-tdma-pf.h>
    #include <ns3/nr-mac-scheduler-tdma-qos.h>
    #include <ns3/nr-mac-scheduler-tdma-rr.h>
    #include <ns3/nr-mac-scheduler-tdma.h>
    #include <ns3/nr-mac-scheduler-ue-info-mr.h>
    #include <ns3/nr-mac-scheduler-ue-info-pf.h>
    #include <ns3/nr-mac-scheduler-ue-info-qos.h>
    #include <ns3/nr-mac-scheduler-ue-info-rr.h>
    #include <ns3/nr-mac-scheduler-ue-info.h>
    #include <ns3/nr-mac-scheduler.h>
    #include <ns3/nr-mac-short-bsr-ce.h>
    #include <ns3/nr-mimo-chunk-processor.h>
    #include <ns3/nr-mimo-matrices.h>
    #include <ns3/nr-mimo-signal.h>
    #include <ns3/nr-net-device.h>
    #include <ns3/nr-no-op-component-carrier-manager.h>
    #include <ns3/nr-no-op-handover-algorithm.h>
    #include <ns3/nr-pdcp-header.h>
    #include <ns3/nr-pdcp-sap.h>
    #include <ns3/nr-pdcp-tag.h>
    #include <ns3/nr-pdcp.h>
    #include <ns3/nr-phy-mac-common.h>
    #include <ns3/nr-phy-sap.h>
    #include <ns3/nr-phy-tag.h>
    #include <ns3/nr-phy.h>
    #include <ns3/nr-pm-search-full.h>
    #include <ns3/nr-pm-search.h>
    #include <ns3/nr-radio-bearer-info.h>
    #include <ns3/nr-radio-bearer-tag.h>
    #include <ns3/nr-rlc-am-header.h>
    #include <ns3/nr-rlc-am.h>
    #include <ns3/nr-rlc-header.h>
    #include <ns3/nr-rlc-sap.h>
    #include <ns3/nr-rlc-sdu-status-tag.h>
    #include <ns3/nr-rlc-sequence-number.h>
    #include <ns3/nr-rlc-tag.h>
    #include <ns3/nr-rlc-tm.h>
    #include <ns3/nr-rlc-um.h>
    #include <ns3/nr-rlc.h>
    #include <ns3/nr-rrc-header.h>
    #include <ns3/nr-rrc-protocol-ideal.h>
    #include <ns3/nr-rrc-protocol-real.h>
    #include <ns3/nr-rrc-sap.h>
    #include <ns3/nr-simple-ue-component-carrier-manager.h>
    #include <ns3/nr-spectrum-phy.h>
    #include <ns3/nr-spectrum-signal-parameters.h>
    #include <ns3/nr-ue-ccm-rrc-sap.h>
    #include <ns3/nr-ue-cmac-sap.h>
    #include <ns3/nr-ue-component-carrier-manager.h>
    #include <ns3/nr-ue-cphy-sap.h>
    #include <ns3/nr-ue-mac.h>
    #include <ns3/nr-ue-net-device.h>
    #include <ns3/nr-ue-phy.h>
    #include <ns3/nr-ue-power-control.h>
    #include <ns3/nr-ue-rrc.h>
    #include <ns3/nr-vendor-specific-parameters.h>
    #include <ns3/realistic-beamforming-algorithm.h>
    #include <ns3/realistic-bf-manager.h>
    #include <ns3/sfnsf.h>
    #include <ns3/distance-based-three-gpp-spectrum-propagation-loss-model.h>
    #include <ns3/traffic-generator-helper.h>
    #include <ns3/xr-traffic-mixer-helper.h>
    #include <ns3/traffic-generator-3gpp-audio-data.h>
    #include <ns3/traffic-generator-3gpp-generic-video.h>
    #include <ns3/traffic-generator-3gpp-pose-control.h>
    #include <ns3/traffic-generator-ftp-single.h>
    #include <ns3/traffic-generator-ngmn-ftp-multi.h>
    #include <ns3/traffic-generator-ngmn-gaming.h>
    #include <ns3/traffic-generator-ngmn-video.h>
    #include <ns3/traffic-generator-ngmn-voip.h>
    #include <ns3/traffic-generator.h>
#endif 