#ifndef NS3_CORE_CONFIG_H
#define NS3_CORE_CONFIG_H

/* #undef HAVE_UINT128_T */
#define HAVE___UINT128_T 1
#define INT64X64_USE_128
/* #undef INT64X64_USE_DOUBLE */
/* #undef INT64X64_USE_CAIRO */
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_DIRENT_H 1
#define HAVE_GETENV 1
#define HAVE_SIGNAL_H 1

#endif // NS3_CORE_CONFIG_H
